name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build executables
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: linux
            ext: ""
          - goos: windows
            ext: ".exe"
          - goos: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
