name: Build Release Binaries

# This workflow builds release binaries for the OpenShield agent.
on:
  release:
    types:
      - created

jobs:
  build:
    name: Build executables
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: linux
            ext: ""
          - goos: windows
            ext: ".exe"
          - goos: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Build
        run: |
          mkdir -p release
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }}${{ matrix.ext }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          name: openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }}
          path: release/openshield-agent-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.tag_name }}${{ matrix.ext }}

      - name: List executables
        run: ls -l ./release

      - name: Upload release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./release/*
          file_glob: true
